spring.application.name=claims-service

spring.datasource.url=jdbc:postgresql://localhost:5432/claims_db
spring.datasource.username=movetrack
spring.datasource.password=localdevpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

claims.approval.supervisor-threshold=1000.00

server.port=8081