spring.application.name=move-entitlement-service

spring.datasource.url=jdbc:postgresql://localhost:5432/move_entitlement_db
spring.datasource.username=movetrack
spring.datasource.password=localdevpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=8082

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest