spring.application.name=move-entitlement-service

spring.datasource.url=jdbc:postgresql://localhost:5432/move_entitlement_db
spring.datasource.username=movetrack
spring.datasource.password=localdevpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true